'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 9/27/2012 4:09:59 PM
Namespace ASDDWebMethods
    '''<summary>
    '''There are no comments for ASNodeConfiguration in the schema.
    '''</summary>
    Partial Public Class ASNodeConfiguration
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new ASNodeConfiguration object.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
    End Class
End Namespace
